name: build-and-test
# See: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

on:
  push:
    branches: [ "core" ]
  pull_request:
    branches: [ "core" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: go version
      - run: go get .
      - run: sudo apt-get install gcc libgl1-mesa-dev xorg-dev
      - run: go build -v ./...
      - run: go test -v ./...
  build-android:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: go version
      - run: go get .
      - { uses: actions/setup-java@v4, with: { distribution: 'temurin', java-version: '21' } }
      - uses: android-actions/setup-android@v3
      - run: make sigi_gui.apk
